version: '3.1'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080"
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "4000:4000"
    restart: always