distributed-systems:
     mongodb:
        replicaset:
           #replicaSetName: docker-rs
           username: admin
           password: admin
           primary: rydell-router-01
           port: 27117
           #port: 9242
           database: wada
           maxPoolSize: 600
           authenticationDb: admin
           authMechanism: SCRAM-SHA-1